SYSADMIN/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from SAAL.views import Login, Logout

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', Login.as_view(), name='login'),
    url(r'^logout/', Logout.as_view(), name='logout'),
    url(r'^usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.conf.urls import url
from usuarios.views import Inicio, Busquedas, CobroRecargo, ControlPresupuestal, VerFactura
from usuarios.views import ImprimirSoporteP, AnularPago, VerCredito
from usuarios.views import ListaViviendas, ListaPropietarios, ReportePdfPagos, Creditos, RegistroCredito
from usuarios.views import RegistroProveedor, Consumo,AsignarMedidor, RegistrarConsumo
from usuarios.views import PazSalvo, ReporteConceptos
from usuarios.views import AgregarVivienda, AgregarPropietario, ReporteCompleto
from usuarios.views import ReporteOrdenesT, ModificarPropietario, ModificarVivienda
from usuarios.views import RegMenCon, EliminarPoblacion, AcuerdoPago
from usuarios.views import VisualizarPropietario, CambioEstado, Estadoscuenta, RegistroCostoM
from usuarios.views import RegistroTarifa,ReporteGastos, ListasGastos
from usuarios.views import OrdenesdeTrabajo, VerOrdenSuspencion, CambioTitular
from usuarios.views import CierreFinanciero, VerConsumo, GeneradorConceptos, GeneradorSuspenciones
from usuarios.views import GenerarGasto, AsignarSubsidio
from usuarios.views import GeneradorFacturas, DesactivarUsuarios, AnularFactura
from usuarios.views import DescargarFactura, DescargaMasivaFacturas, VisualizarVivienda, BuscarSolicitud
from usuarios.views import ModificarAcueducto, ListaPqrs, RegistroPqr, VerPqr
from usuarios.views import RespuestaPqrs, ReporteCierre, ReporteConsumos, PlantillaMedicion
from usuarios.views import RegistroMedidor, ValidarIdentificacionView, Pruebas
from usuarios.views import CambiarContraUsuario, GeneradorFacturasIndividual,ReporteRetiro, DescargarFacturasMasivas

urlpatterns = [
    url(r'^inicio/', Inicio.as_view(), name='inicio'),
    url(r'^pruebas/', Pruebas.as_view(), name='pruebas'),
    url(r'^listaviviendas/', ListaViviendas.as_view(), name='listaviviendas'),
    url(r'^listapropietarios/', ListaPropietarios.as_view(), name='listapropietarios'),
    url(r'^agregarvivienda', AgregarVivienda.as_view(), name='agregarvivienda'),
    url(r'^agregarpropietario/', AgregarPropietario.as_view(), name='agregarpropietario'),
    url(r'^modificarpropietario/(?P<IdPropietario>\w+)', ModificarPropietario.as_view(), name='modificarpropietario'),
    url(r'^modificarvivienda/(?P<idvivienda>\w+)', ModificarVivienda.as_view(), name='modificarvivienda'),
    url(r'^verpropiedario/(?P<idpropietario>\w+)', VisualizarPropietario.as_view(), name='verpropietario'),
    url(r'^vervivienda/(?P<idvivienda>\w+)', VisualizarVivienda.as_view(), name='vervivienda'),
    url(r'^estadoscuenta/', Estadoscuenta.as_view(), name='estadoscuenta'),
    url(r'^reportecompleto/', ReporteCompleto.as_view(), name='reportecompleto'),
    url(r'^reportepagos/', ReportePdfPagos.as_view(), name='reportepagos'),
    url(r'^busquedas/', Busquedas.as_view(), name='busquedas'),
    url(r'^controlpresupuestal/', ControlPresupuestal.as_view(), name='controlpresupuestal'),
    url(r'^generargasto/', GenerarGasto.as_view(), name='generargasto'),
    url(r'^cambio/(?P<IdSoGa>\w+)', BuscarSolicitud.as_view(), name='cambio'),
    url(r'^listadogastos/', ListasGastos.as_view(), name='listadogastos'),
    url(r'^registromedidor/', RegistroMedidor.as_view(), name='registromedidor'),
    url(r'^registrocostomatricula/', RegistroCostoM.as_view(), name='registrocostomatricula'),
    url(r'^registrotarifa/', RegistroTarifa.as_view(), name='registrotarifa'),
    url(r'^verfactura/', VerFactura.as_view(), name='verfactura'),
    url(r'^registropqrs/', RegistroPqr.as_view(), name='registropqrs'),
    url(r'^listapqrs/', ListaPqrs.as_view(), name='listapqrs'),
    url(r'^verpqr/(?P<idpqr>\w+)', VerPqr.as_view(), name='verpqr'),
    url(r'^generadorfacturas/', GeneradorFacturas.as_view(), name='generadorfacturas'),
    url(r'^ordenestrabajo/', OrdenesdeTrabajo.as_view(), name='ordenestrabajo'),
    url(r'^anularfactura/', AnularFactura.as_view(), name='anularfactura'),
    url(r'^respuestapqr/(?P<idsolicitud>\w+)', RespuestaPqrs.as_view(), name='respuestapqr'),
    url(r'^verordensus/(?P<IdOrden>\w+)', VerOrdenSuspencion.as_view(), name='verordensus'),
    url(r'^descargarfactura/(?P<IdFactura>\w+)', DescargarFactura.as_view(), name='descargarfactura'),
    url(r'^facturaindividual/(?P<IdVivienda>\w+)', GeneradorFacturasIndividual.as_view(), name='facturaindividual'),
    url(r'^facturamasiva/', DescargaMasivaFacturas.as_view(), name='facturamasiva'),
    url(r'^reporteordenes', ReporteOrdenesT.as_view(), name='reporteordenes'),
    url(r'^cambiotitular/(?P<IdVivienda>\w+)', CambioTitular.as_view(), name='cambiotitular'),
    url(r'^modificarempresa', ModificarAcueducto.as_view(), name='modificarempresa'),
    url(r'^desacusuario/(?P<usuid>\w+)', DesactivarUsuarios.as_view(), name='desacusuario'),
    url(r'^elipoblacion', EliminarPoblacion.as_view(), name='elipoblacion'),
    url(r'^cambiarcontrasena/(?P<usuid>\w+)', CambiarContraUsuario.as_view(), name='cambiarcontrasena'),
    url(r'^cambioestado/(?P<IdVivienda>\w+)', CambioEstado.as_view(), name='cambioestado'),
    url(r'^cierrefinanciero', CierreFinanciero.as_view(), name='cierrefinanciero'),
    url(r'^reportecierre', ReporteCierre.as_view(), name='reportecierre'),
    url(r'^reportegastos', ReporteGastos.as_view(), name='reportegastos'),
    url(r'^imprimirpago/(?P<IdPago>\w+)', ImprimirSoporteP.as_view(), name='imprimirpago'),
    url(r'^pazysalvo/(?P<matricula>\w+)', PazSalvo.as_view(), name='pazysalvo'),
    url(r'^cobrorecargo', CobroRecargo.as_view(), name='cobrorecargo'),
    url(r'^anularpago', AnularPago.as_view(), name='anularpago'),
    url(r'^credito', Creditos.as_view(), name='credito'),
    url(r'^registrocredito', RegistroCredito.as_view(), name='registrocredito'),
    url(r'^registroproveedor', RegistroProveedor.as_view(), name='registroproveedor'),
    url(r'^vercredito/(?P<idcredito>\w+)', VerCredito.as_view(), name='vercredito'),
    url(r'^novedadretiro/(?P<matricula>\w+)', ReporteRetiro.as_view(), name='novedadretiro'),
    url(r'^consumos', Consumo.as_view(), name='consumos'),
    url(r'^asignarmedidor/(?P<IdMedidor>\w+)', AsignarMedidor.as_view(), name='asignarmedidor'),
    url(r'^registrarconsumo', RegistrarConsumo.as_view(), name='registrarconsumo'),
    url(r'^verconsumo/(?P<matricula>\w+)', VerConsumo.as_view(), name='verconsumo'),
    url(r'^crearconceptos', GeneradorConceptos.as_view(), name='crearconceptos'),
    url(r'^varias/', GeneradorSuspenciones.as_view(), name='varias'),
    url(r'^rconsumos/', ReporteConsumos.as_view(), name='rconsumos'),
    url(r'^reporteconceptos', ReporteConceptos.as_view(), name='reporteconceptos'),
    url(r'^pmedicion/', PlantillaMedicion.as_view(), name='pmedicion'),
    url(r'^regmencon/', RegMenCon.as_view(), name='regmencon'),
    url(r'^acuerdosdepago/', AcuerdoPago.as_view(), name='acuerdosdepago'),
    url(r'^validaciones/', ValidarIdentificacionView.as_view(), name='validaciones'),
    url(r'^asignarsubsidio/(?P<matricula>\w+)', AsignarSubsidio.as_view(), name='asignarsubsidio'),
    url(r'^masivo/', DescargarFacturasMasivas.as_view(), name='masivo'),
]

usuarios/views.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from SAAL.models import Usuario, Tarifa, Credito, Novedades
from SAAL.models import Poblacion, Facturas, Ciclo, EstadoCuenta, AcuerdosPago, FacturasConceptos
from SAAL.models import Vivienda, SolicitudGastos, Propietario, Medidores, Pqrs, RespuestasPqrs
from SAAL.models import Permisos, Pagos, Cierres, Acueducto, ValorMatricula, ConsumosMensual
from SAAL.models import Proveedor,Asignacion, Consumos, Conceptos, ConceptosFacturados, OrdenesTrabajo, Ciclos, Sectores
from SAAL.forms import FormAgregarGasto, FormRegistroPqrs, RegistroVivienda, Subsidio
from SAAL.forms import AcueductoAForm, CostoMForm, FormRespuestaPqrs, FormAsignarMedidor
from SAAL.forms import RegistroPropietario, TarifasForm, ModificaPropietario, FormRegistroCredito, FormRegistroProveedor
from SAAL.forms import CambioFormEstado, AcueductoForm, GastosForm, MedidoresForm, ModificaVivienda
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect,JsonResponse
from django.urls import reverse
from django.contrib import auth
from datetime import datetime, timedelta
from django.http import HttpResponse
from openpyxl import Workbook
import openpyxl
import qrcode
from openpyxl.drawing.image import Image
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from usuarios.ConectorPython import *
from django.db.models import Sum
from calendar import monthrange, month_name
import locale
from django.db.models import Count, Q
from io import BytesIO
import zipfile


# Reemplaza estos valores con tus credenciales de Google Mail
username = 'sistemas.acueducto.caimalito@gmail.com'

#SECTORES
SECTOR1 = 'Pasonivel Viejo'
SECTOR2 = 'Pasonivel Destapada'
SECTOR3 = 'Caimalito Centro'
SECTOR4 = 'Barrio Nuevo'
SECTOR5 = '20 de julio'
SECTOR6 = 'Carbonera'
SECTOR7 = 'Hacienda'

# ESTADOS PRERIOS
ESTADOS1 = 'Operativo'
ESTADOS2 = 'Suspendido'
ESTADOS3 = 'Mantenimiento'
ESTADOS4 = 'Retirado'

#NOVEDADES
NOVEDAD1 = 'Cerrada'

# Tiempos de facturacion
DIASFACTURACION = 10
DIASPARASUSPENCION = 15
# permisos
CT = 'AC'
# TARIFA
TARIFA = 10000
# ------------
EF = 'Emitida'
EPC = 'Se registro propietario'
EPM = 'Se modifico propietario'
DESC = 'Null'
ECV = 'Se registro vivienda'
EMV = 'Se modifico vivienda'
# Tipo novedades
DES = 'Descuento'
ADI = 'Adicion'
# estados suspenciones
SA = 'Anulada'
SP = 'Pendiente'
SJ = 'Ejecutada'
TARIFASUSPENCION = 5000
# estados ciclos
EC = 'SIN PAGAR'
EC2 = 'PAGO'
EC3 = 'ANULADA'
# EstadosFacturas
FE = 'Emitida'
FV = 'Vencida'
FP = 'Paga'
FA = 'Anulada'
# Estadoscuentasdecobro
Estadocue = 'Mantenimiento'
# otros
REPORTESUSPEN = 'Suspedido'
# sectores
S1 = 'Pasonivel Viejo'
S2 = 'Pasonivel Destapada'
S3 = 'Caimalito Centro'
S4 = 'Barrio Nuevo'
S5 = '20 de julio'

# ESTADOS PRERIOS
E1 = 'Operativo'
E2 = 'Suspendido'
E3 = 'Retirado'
E4 = 'En construcion'

C1 = 'Ciclo 1'
C2 = 'Ciclo 2'
C3 = 'Ciclo 3'
C4 = 'Ciclo 4'

DESCOBRO = 'Concepto matricula'
COBROCONSUMO = 'Cobro por consumo'
ESTCOBRO = 'Pendiente'
ESTCOBRO2 = 'Pago'
ESTADO1 = "Pendiente"
ESTADO2 = "Aprobada"
ESTADO3 = "Anulada"

class Inicio(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'usuarios/inicio.html'
    form_class = AcueductoForm

    def get(self, request):
        try:
            version = open('static/serial/Version.txt', 'r')
            versionp = version.read()
            version2 = open('static/serial/NombreProyecto.txt', 'r')
            nombreproyecto = version2.read()
            version3 = open('static/serial/NombreProyectoL.txt', 'r')
            nombreproyectol = version3.read()

            hoy = datetime.now()
            usuario = Usuario.objects.get(usuid=request.user.pk)
            idacueducto = usuario.IdAcueducto
            tipousuario = usuario.TipoUsuario
            acueducto = Acueducto.objects.get(IdAcueducto=idacueducto)
            nombreacueducto = acueducto.Sigla
            logo = acueducto.logo
            usuarios = Usuario.objects.filter(IdAcueducto=idacueducto)
            novedades = Novedades.objects.filter(IdAcueducto=idacueducto).order_by("-IdNovedad")[:6]
            lpagos = Pagos.objects.filter(IdAcueducto=idacueducto).order_by("-IdPago")[:4]
            # Obtener la fecha actual
            fechaexp = datetime.today()
            ciclo = fechaexp.month
            ano1 = fechaexp.year

            # Calcular el primer y último día del mes
            primer_dia = datetime(ano1, ciclo, 1)
            ultimo_dia = datetime(ano1, ciclo, monthrange(ano1, ciclo)[1], 23, 59, 59)

            # Consultar los pagos en el rango de fechas
            pagos = Pagos.objects.filter(
                FechaPago__gte=primer_dia,
                FechaPago__lte=ultimo_dia,
                IdAcueducto=idacueducto,
                IdUsuario=usuario
            )
            facturaspagas = Pagos.objects.filter(
                FechaPago__gte=primer_dia,
                FechaPago__lte=ultimo_dia,
                IdAcueducto=idacueducto,
                IdUsuario=usuario
            ).count()
            pago0 = pagos.aggregate(total=Sum('ValorPago'))['total'] or 0

            viviendas = Vivienda.objects.filter(EstadoServicio='Operativo',IdAcueducto=idacueducto) | Vivienda.objects.filter(EstadoServicio='Mantenimiento',IdAcueducto=idacueducto)| Vivienda.objects.filter(EstadoServicio='Suspendido',IdAcueducto=idacueducto)
            personas = 0
            for i in viviendas:
                valor = int(i.CantHabitantes)
                personas += valor

            suscriptoresactivos = Vivienda.objects.filter(EstadoServicio='Operativo',IdAcueducto=idacueducto) | Vivienda.objects.filter(EstadoServicio='Suspendido',IdAcueducto=idacueducto)
            suscriptores = 0
            for i in suscriptoresactivos:
                valor = 1
                suscriptores += valor

            operativos = Vivienda.objects.filter(EstadoServicio='Operativo', IdAcueducto=idacueducto).count()
            suspendidos = Vivienda.objects.filter(EstadoServicio='Suspendido', IdAcueducto=idacueducto).count()
            retirados = Vivienda.objects.filter(EstadoServicio='Retirado', IdAcueducto=idacueducto).count()

            #estratos
            estr1 = Vivienda.objects.filter(Estrato='1', IdAcueducto=idacueducto).count()
            estr2 = Vivienda.objects.filter(Estrato='2', IdAcueducto=idacueducto).count()
            estr3 = Vivienda.objects.filter(Estrato='3', IdAcueducto=idacueducto).count()
            estr4 = Vivienda.objects.filter(Estrato='4', IdAcueducto=idacueducto).count()
            estr5 = Vivienda.objects.filter(Estrato='5', IdAcueducto=idacueducto).count()
            comercial = Vivienda.objects.filter(Estrato='Comercial', IdAcueducto=idacueducto).count()
            industrial = Vivienda.objects.filter(Estrato='Industrial', IdAcueducto=idacueducto).count()
            especial = Vivienda.objects.filter(Estrato='Especial', IdAcueducto=idacueducto).count()
            oficial = Vivienda.objects.filter(Estrato='Oficial', IdAcueducto=idacueducto).count()

            aportefijo = Vivienda.objects.filter(EstadoServicio='Operativo', IdAcueducto=idacueducto,TipoRecaudo='Aporte fijo').count()
            especiala = Vivienda.objects.filter(EstadoServicio='Operativo', IdAcueducto=idacueducto,TipoRecaudo='Especial').count()
            micro = Vivienda.objects.filter(EstadoServicio='Operativo', IdAcueducto=idacueducto,TipoRecaudo='Medicion').count()
            subsidio = Vivienda.objects.filter(EstadoServicio='Operativo', IdAcueducto=idacueducto,
                                            Subsidio='Si').count()

            pqrs = Pqrs.objects.filter(Estado='Pendiente', IdAcueducto=idacueducto).count()

            hoy = datetime.today().date()
            inicio_dia2 = datetime(hoy.year, hoy.month, hoy.day, 0, 0, 0)  # 00:00:00
            fin_dia2 = datetime(hoy.year, hoy.month, hoy.day, 23, 59, 59)  # 23:59:59
            # Consultar los pagos ingresados hoy
            pagos_hoy = Pagos.objects.filter(
                FechaPago__gte=inicio_dia2,
                FechaPago__lte=fin_dia2,
                IdAcueducto=idacueducto,
                IdUsuario=usuario
            )

            # Calcular el total de pagos ingresados hoy
            total_pagos_hoy = pagos_hoy.aggregate(total=Sum('ValorPago'))['total'] or 0
            return render(request,
                          self.template_name, {'tipousuario': tipousuario, 'nombreproyecto': nombreproyecto,'lpagos':lpagos,
                                               'nombreproyectol': nombreproyectol, 'acueducto': nombreacueducto,'pagoshoy':int(total_pagos_hoy),
                                               'versionp': versionp,'personas':personas,'nit':idacueducto,'facturaspagas':facturaspagas,
                                               'novedades': novedades, 'pagos': int(pago0),'suscriptores':suscriptores, 'logo':logo,
                                               'foto': usuario.fotoUsuario,'usuarios': usuarios,'celular': usuario.celular,
                                               'departamento': usuario.Departamento,'cargo': usuario.Cargo, 'fechac': usuario.FechaCreacion,
                                               'ultimo': hoy, 'retirados': retirados,'suspendidos': suspendidos,'operativos':operativos,
                                               'uno': estr1,'dos':estr2,'tres':estr3,'cuatro':estr4,'cinco':estr5,'especial':especial,'industrial':industrial,
                                               'oficial':oficial,'comercial':comercial,'pqrs': pqrs,

usuarios/templates/usuarios/asignacionmedidor.html
{% extends 'usuarios/base_usuario3.html' %}
{% load static %}
{% block styles %}

{% endblock %}
{%block title %} <title>Registro Tarifa</title> {%endblock%}
{% block content %}
{% include 'usuarios/alerts.html' %}
<!-- Titulo -->
      <div class="page-wrapper">
        <div class="container-fluid">
          <!-- Page title -->
          <div class="page-header d-print-none">
            <div class="row align-items-center">
              <div class="col">
                <!-- Page pre-title -->
                <div class="page-pretitle">
                  Modulo
                </div>
                <h2 class="page-title">
                  Registro de usuarios - SAI
                </h2>
              </div>
            </div>
          </div>
        </div>
      </div>
<br>
<div class="card-body">
<div class="row">
    <div class="col-sm-3">
        
    </div>
    <div class="col-sm-6">
    	<div class="row">
    		        <form method="post" enctype="multipart/form-data" class="card">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="card-body">
            {% for field in form %}
            <div class="row">
                <div class="col-xl-12">
                    <div class="row">
                        <div class="col-md-6 col-xl-12">
                            <div class="mb-3">
                            {{ field.errors }}
                              <label class="form-label">{{ field.label }}</label>
                              {{ field }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="col-sm-12" style="margin-top: 1rem;">
                    <button style="width: 100%;" type="submit" class="btn btn-primary ">Registrar</button>
                </div>

            </div>
        </div>
    </form>
    	</div>
    	<div class="row">
    		 <div class="col-sm-12" style="margin-top: 1rem;">
                    <button style="width: 100%;" onclick="window.location='{% url 'usuarios:consumos' %}'" class="btn btn-primary ">Cancelar</button>
                </div>
    	</div>

    </div>
                   
    </div>
    </div>                 

{% endblock %}
{% block scripts %}

{% endblock %}

usuarios/templates/usuarios/cobrorecargo.html
{% extends 'usuarios/base_usuario3.html' %}
{% load static %}
{% block styles %}
{% endblock %}
{%block title %} <title>Recargos por mora</title> {%endblock%}
{% block content %}
{% include 'usuarios/alerts.html' %}
<!-- Titulo -->
      <div class="page-wrapper">
        <div class="container-fluid">
          <!-- Page title -->
          <div class="page-header d-print-none">
            <div class="row align-items-center">
              <div class="col">
                <!-- Page pre-title -->
                <div class="page-pretitle">
                  Modulo
                </div>
                <h2 class="page-title">
                  Generar cobro de masivo de aportes por mora
                </h2>
              </div>
              <div class="col-auto ms-auto d-print-none">
                <div class="btn-list">
                    <div class="col-auto">
                        <a href="{% url 'usuarios:estadoscuenta' %}" class="btn btn-sm btn-indigo btn-pill w-100">
                                      Volver</a>
                    </div>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
            <div class="page-body">
            <div class="container-xl">
              <div class="row row-cards">
                        <div class="col-md-4 col-lg-4">
                        </div>
                        <div class="col-md-4 col-lg-4">

                            <div class="card">
                                 <div class="row">
                                <div class="col-sm-12 text-center">
                                    <img style="width: 40%" alt="" src="{% static 'images/alerta.png' %}">
                                </div>
                            </div>
                                <div class="card-body">
                                   <h3 class="subheader">Opciones disponibles</h3>
                                   <dl class="row">
                                      <dt class="col-6">Numero de recargos:</dt>
                                      <dd class="col-6">{{cont}}</dd>
                                    </dl>
                                   <div class="row">
                                        <div class="col-3">
                                            
                                        </div>
                                        <div class="col-6">
                                            <a href="" class="btn btn-indigo w-100" data-bs-toggle="modal" data-bs-target="#modal-danger"> Continuar</a>
                                        </div>
                                        <div class="col-3">
                                            
                                        </div>
                                   </div>
                                   
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4">
                        </div>                                   
            </div>
            </div>
          </div>  
        </div>
    <div class="modal modal-blur fade" id="modal-danger" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
        <div class="modal-content">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          <div class="modal-status bg-danger"></div>
          <div class="modal-body text-center py-4">
            <!-- Download SVG icon from http://tabler-icons.io/i/alert-triangle -->
            <svg xmlns="http://www.w3.org/2000/svg" class="icon mb-2 text-danger icon-lg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 9v2m0 4v.01" /><path d="M5 19h14a2 2 0 0 0 1.84 -2.75l-7.1 -12.25a2 2 0 0 0 -3.5 0l-7.1 12.25a2 2 0 0 0 1.75 2.75" /></svg>
            <h3>Estas seguro?</h3>
            <div class="text-muted">¿Realmente quieres anular masivamente las ordenes de suspencion y el cambio de estado de la facturacion vigente a vencida? Lo que hagas no se puede deshacer.</div>
          </div>
          <div class="modal-footer">
            <div class="w-100">
              <div class="row">
                <div class="col"><a href="#" class="btn w-100" data-bs-dismiss="modal">
                    Cancelar
                  </a></div>
                <div class="col">
                    <form method="post" role="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <button  style="width: 100%;" type="submit" class="btn btn-primary">Finalizar</button>
                    </form>  
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}
{% block scripts %}
{% endblock %}

usuarios/templates/usuarios/registromedidor.html
{% extends 'usuarios/base_usuario2.html' %}
{% load static %}
{% block styles %}
{% endblock %}
{%block title %} <title>Modulo - RM</title> {%endblock%}
{% block content %}
	{% include 'usuarios/alerts.html' %}
<div class="row">
    <div class="col-sm-8">
        <h4 class="text-gray-800">Asignar medidor</h4>
    </div>
     <div class="col-sm-4">
        <button class="btn btn-primary btn-sm ml-auto float-right" style="margin-right: 0.5rem;" onclick="window.location='{% url 'usuarios:vervivienda' matricula %}'">Volver</button>
    </div>
</div>
			<div class="row" style="margin-bottom: 0.5rem;">
				<div class="col-sm-3">
					
				</div>
				<div class="col-sm-6" style="font-size: 1rem;">
					<div class="panel">
						<div class="panel-body no-padding">
							<div class="wizard-content panel no-margin no-border-hr no-border-b no-padding-hr">
									<form method="post" enctype="multipart/form-data">
										{% csrf_token %}
										{{ form.non_field_errors }}
					                    {% for field in form %}
					                        <div class="form-group no-padding-t no-border-t panel-padding-h">
					                            {{ field.errors }}
					                            <label for="jq-validation-url" class="col-sm-12 control-label">
					                                <strong>{{ field.label }}</strong>
					                            </label>
					                            <div class="col-sm-12">
					                                {{ field }}
					                            </div>
					                        </div>
					                    {% endfor %}
										<button type="submit" class="btn btn-primary btn-sm" style="width: 100%;">Registrar</button>
									</form> <!-- / .wizard-pane -->
								</div> <!-- / .wizard-content -->
							</div> <!-- / .wizard -->
						</div>
					</div>
					<div class="col-sm-3">
					
				</div>
				</div>
{% endblock %}
{% block scripts %}
{% endblock %}